---
title: "DataWrangling"
author: "Jacob Freedman and Logan Dye"
date: "2022-12-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

##Setup
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=45), tidy=TRUE)

#Loading packages
library(tidyverse)
library(dplyr)
library(lubridate)
library(sf)
library(mapview)
library(cowplot)
library(maps)
library(trend)
library(Kendall)
library(tseries)

mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

```

##Gathering Datasets and Wrangling Date Columns

```{r}
#Reading in Pika Demography and Climate datasets
Pika_Raw <- read.csv("./Data/Raw/pika_demography.cr.data.csv", stringsAsFactors = TRUE)
Climate_Raw <- read.csv("./Data/Raw/d-1cr23x-cr1000.daily.ml.data.csv", stringsAsFactors = TRUE)

#Setting proper dates
class(Pika_Raw$date)
Pika_Raw$date <- as.Date(Pika_Raw$date, format = "%Y-%m-%d")
class(Pika_Raw$date)

class(Climate_Raw$date)
Climate_Raw$date <- as.Date(Climate_Raw$date, format = "%Y-%m-%d")
class(Climate_Raw$date)
Climate_Raw$year <- as.character(Climate_Raw$year) %>%
  as.Date.character(Climate_Raw$year, format = "%Y")
```
 
##Climate Data Wrangling
  
```{r}
#Wrangling climate dataset for focal period
Climate_08to18 <- Climate_Raw %>%
mutate(Year = year(year), Month = month(date)) %>%
  select(LTER_site:date, airtemp_avg, Year, Month) %>%
  filter(Year >= "2008", Year <= "2018")

Climate_08to18_clean <- 
  Climate_08to18 %>% 
  mutate(airtemp_avg_interpolated =   zoo::na.approx(airtemp_avg))

Climate_Means_08to18 <- Climate_08to18_clean %>%
  group_by(Year) %>%
  summarise(
    Mean_Avg_Temp = mean(airtemp_avg_interpolated))

Climate_Means_08to18_Refined <- Climate_Means_08to18 %>%
  filter(Year!= 2009)
```

```{r}
#Isolating individual Pika captures. We combined all tag components into a single identifier (PikaID) to sort out recaptures from the same year. 
Pika_Processed <- Pika_Raw %>%
  mutate(PikaID = paste(num_r_ear,"",num_l_ear,"",code_r_ear,"",code_l_ear), Year = year(date)) %>%
  select(LTER_site:date, Year, easting:num_l_ear, PikaID) %>%
  group_by(Year) %>%
  subset(tag_type =="A" | tag_type == "C3") %>%
  subset(PikaID!= "NS  NS  NS  NS" & PikaID!= "NA  NA  NA  NA")

#Created dataframes for each year of data to count unique values.

Pika_2008 <- Pika_Processed %>%
  filter(Year == 2008)
length(unique(Pika_2008$PikaID))

Pika_2010 <- Pika_Processed %>%
  filter(Year == 2010)
length(unique(Pika_2010$PikaID))

Pika_2011 <- Pika_Processed %>%
  filter(Year == 2011)
length(unique(Pika_2011$PikaID))

Pika_2012 <- Pika_Processed %>%
  filter(Year == 2012)
length(unique(Pika_2012$PikaID))

Pika_2013 <- Pika_Processed %>%
  filter(Year == 2013)
length(unique(Pika_2013$PikaID))

Pika_2014 <- Pika_Processed %>%
  filter(Year == 2014)
length(unique(Pika_2014$PikaID))

Pika_2015 <- Pika_Processed %>%
  filter(Year == 2015)
length(unique(Pika_2015$PikaID))

Pika_2016 <- Pika_Processed %>%
  filter(Year == 2016)
length(unique(Pika_2016$PikaID))

Pika_2017 <- Pika_Processed %>%
  filter(Year == 2017)
length(unique(Pika_2017$PikaID))

Pika_2018 <- Pika_Processed %>%
  filter(Year == 2018)
length(unique(Pika_2018$PikaID))

Pika_2019 <- Pika_Processed %>%
  filter(Year == 2019)
length(unique(Pika_2019$PikaID))

Pika_2020 <- Pika_Processed %>%
  filter(Year == 2020)
length(unique(Pika_2020$PikaID))

#Taking value from count and putting it into a data frame. Each annual data frame has two values (year and number of captures).

Pika_2008_Count <- as.data.frame(table(Pika_2008$Year))
Pika_2010_Count <- as.data.frame(table(Pika_2010$Year))
Pika_2011_Count <- as.data.frame(table(Pika_2011$Year))
Pika_2012_Count <- as.data.frame(table(Pika_2012$Year))
Pika_2013_Count <- as.data.frame(table(Pika_2013$Year))
Pika_2014_Count <- as.data.frame(table(Pika_2014$Year))
Pika_2015_Count <- as.data.frame(table(Pika_2015$Year))
Pika_2016_Count <- as.data.frame(table(Pika_2016$Year))
Pika_2017_Count <- as.data.frame(table(Pika_2017$Year))
Pika_2018_Count <- as.data.frame(table(Pika_2018$Year))
Pika_2019_Count <- as.data.frame(table(Pika_2019$Year))
Pika_2020_Count <- as.data.frame(table(Pika_2020$Year))

#Using rbind to compile 1 data frame of annual captures.

Pika_Total_Count <- rbind(Pika_2008_Count, Pika_2010_Count, Pika_2011_Count, Pika_2012_Count, Pika_2013_Count, Pika_2014_Count, Pika_2015_Count, Pika_2016_Count, Pika_2017_Count, Pika_2018_Count, Pika_2019_Count, Pika_2020_Count)

colnames(Pika_Total_Count) <- c('Year','Captures')

#Filtering to get Pika dataset to match climate dataset
  
Pika_Count_08to18 <- rbind(Pika_2008_Count, Pika_2010_Count, Pika_2011_Count, Pika_2012_Count, Pika_2013_Count, Pika_2014_Count, Pika_2015_Count, Pika_2016_Count, Pika_2017_Count, Pika_2018_Count)

colnames(Pika_Count_08to18) <- c('Year','Captures')

#Merging Pika data with climate data to prepare for analysis

Pika_Temperature <- merge(Pika_Count_08to18, Climate_Means_08to18_Refined, by.x = "Year", by.y = "Year")
```

##Flea Data Wrangling

```{r}
# Initial wrangling for flea data. In this code chuck I create two data frames isolating flea and mite data respectively. 

#Isolating individual Pika captures, and including flea data. We created a specific PikaID to account for repeated captures of the same individual within the same year. 
Fleas_Pika_Processed <- Pika_Raw %>%
  mutate(PikaID = paste(num_r_ear,"",num_l_ear,"",code_r_ear,"",code_l_ear), Year = year(date)) %>%
  select(LTER_site:date, Year, easting:num_l_ear, fleas_samp, fleas_obs, PikaID) %>%
  group_by(Year) %>%
  subset(tag_type =="A" | tag_type == "C3") %>%
  subset(PikaID!= "NS  NS  NS  NS" & PikaID!= "NA  NA  NA  NA")

# Convert fleas_obs and fleas_samp columns from factor to numeric. 

Fleas_Pika_Processed$fleas_obs <- as.numeric(as.character(Fleas_Pika_Processed$fleas_obs))
Fleas_Pika_Processed$fleas_samp <- as.numeric(as.character(Fleas_Pika_Processed$fleas_samp))

#remove NA's and create two datasets. One with all flea observations and one with all flea's sampled.

Fleas_obs_NARemoved <- Fleas_Pika_Processed %>%
  select(date, Year, fleas_obs, PikaID) %>%
  na.omit(fleas_obs)

Fleas_samp_NARemoved <- Fleas_Pika_Processed %>%
  select(date, Year, fleas_samp, PikaID) %>%
  na.omit(fleas_samp)
```

```{r}
#Finding the mean fleas observed per individual Pika by year. We separate the data frame by year because the same Pika may be sampled multiple times in the same year or multiple times over multiple years. If we did a group_by(PikaID) for the entire data set we would group Pika observations over multiple years. 

Fleas_obs_2010 <- Fleas_obs_NARemoved %>%
  filter(Year == 2010) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2011 <- Fleas_obs_NARemoved %>%
  filter(Year == 2011) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2012 <- Fleas_obs_NARemoved %>%
  filter(Year == 2012) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2013 <- Fleas_obs_NARemoved %>%
  filter(Year == 2013) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2014 <- Fleas_obs_NARemoved %>%
  filter(Year == 2014) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2015 <- Fleas_obs_NARemoved %>%
  filter(Year == 2015) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2016 <- Fleas_obs_NARemoved %>%
  filter(Year == 2016) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2017 <- Fleas_obs_NARemoved %>%
  filter(Year == 2017) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2018 <- Fleas_obs_NARemoved %>%
  filter(Year == 2018) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2019 <- Fleas_obs_NARemoved %>%
  filter(Year == 2019) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

Fleas_obs_2020 <- Fleas_obs_NARemoved %>%
  filter(Year == 2020) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Obs = mean(fleas_obs),
    Year = unique(Year)
  )

#combine the yearly flea observations into one data frame. The data no longer has repeated Pika observations within the same year. 

Fleas_Obs_10to20 <-
  rbind(Fleas_obs_2010, Fleas_obs_2011, Fleas_obs_2012, Fleas_obs_2013, Fleas_obs_2014, Fleas_obs_2015, Fleas_obs_2016, Fleas_obs_2017, Fleas_obs_2018, Fleas_obs_2019, Fleas_obs_2020)

#fleas observed with years within the climate data range. 

Fleas_Obs_Climate_Years <-
  rbind(Fleas_obs_2010, Fleas_obs_2011, Fleas_obs_2012, Fleas_obs_2013, Fleas_obs_2014, Fleas_obs_2015, Fleas_obs_2016, Fleas_obs_2017, Fleas_obs_2018)
```

```{r}
#Completing the same process of splitting the data into years, grouping by individual Pika tag IDs, and finding yearly means. This time for fleas sampled, rather than fleas observed. 

Fleas_samp_2008 <- Fleas_samp_NARemoved %>%
  filter(Year == 2008) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2010 <- Fleas_samp_NARemoved %>%
  filter(Year == 2010) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2011 <- Fleas_samp_NARemoved %>%
  filter(Year == 2011) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2012 <- Fleas_samp_NARemoved %>%
  filter(Year == 2012) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2013 <- Fleas_samp_NARemoved %>%
  filter(Year == 2013) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2014 <- Fleas_samp_NARemoved %>%
  filter(Year == 2014) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2015 <- Fleas_samp_NARemoved %>%
  filter(Year == 2015) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2016 <- Fleas_samp_NARemoved %>%
  filter(Year == 2016) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2017 <- Fleas_samp_NARemoved %>%
  filter(Year == 2017) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2018 <- Fleas_samp_NARemoved %>%
  filter(Year == 2018) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2019 <- Fleas_samp_NARemoved %>%
  filter(Year == 2019) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

Fleas_samp_2020 <- Fleas_samp_NARemoved %>%
  filter(Year == 2020) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_Flea_Samp = mean(fleas_samp),
    Year = unique(Year)
  )

#combine the yearly flea samples into one data frame which no longer has repeated Pika observations within the same year.

Fleas_Samp_08to20 <- 
  rbind(Fleas_samp_2008, Fleas_samp_2010, Fleas_samp_2011, Fleas_samp_2012, Fleas_samp_2013, Fleas_samp_2014, Fleas_samp_2015, Fleas_samp_2016, Fleas_samp_2017, Fleas_samp_2018, Fleas_samp_2019, Fleas_samp_2020)

#fleas observed with years within the climate data range. 

fleas_Samp_Climate_Years <-
  rbind(Fleas_samp_2008, Fleas_samp_2010, Fleas_samp_2011, Fleas_samp_2012, Fleas_samp_2013, Fleas_samp_2014, Fleas_samp_2015, Fleas_samp_2016, Fleas_samp_2017, Fleas_samp_2018)
```

```{r}
#Create data frames with the yearly average fleas observations and samples. 

#Total Flea Observation by year
Yearly_Fleas_Obs_10to20_pipe <- Fleas_Obs_10to20 %>%
  group_by(Year) %>%
  summarise(Yearly_Flea_Obs = mean(Mean_Flea_Obs),
            format(round(Yearly_Flea_Obs, 2), nsmall = 2)) 

#change the column names. 

colnames(Yearly_Fleas_Obs_10to20_pipe) <- c("Year", "Average", "Avg_Flea_Obs")

#select for the variables I want in my processed data frame.

Yearly_Flea_Obs_10to20 <- Yearly_Fleas_Obs_10to20_pipe %>%
  select(Year, Avg_Flea_Obs) 

Yearly_Flea_Obs_10to20$Avg_Flea_Obs <- 
  as.numeric(Yearly_Flea_Obs_10to20$Avg_Flea_Obs)

#Total Flea Observations by year within climate data range 

Yearly_Flea_Obs_10to18 <- Yearly_Flea_Obs_10to20 %>%
  filter(Year!= 2019,
         Year!= 2020)

#Total average Flea Samples by year

Yearly_Fleas_Samp_08to20_pipe <- Fleas_Samp_08to20 %>%
  group_by(Year) %>%
  summarise(Yearly_Flea_Samp = mean(Mean_Flea_Samp),
            format(round(Yearly_Flea_Samp, 2), nsmall = 2)) 

colnames(Yearly_Fleas_Samp_08to20_pipe) <- c("Year", "Average", "Avg_Fleas_Samp")

Yearly_Fleas_Samp_08to20 <- Yearly_Fleas_Samp_08to20_pipe %>%
  select(Year, Avg_Fleas_Samp)

#Total average Flea Samples by year within climate data range

Yearly_Fleas_Samp_08to18 <- Yearly_Fleas_Samp_08to20 %>%
  filter(Year!= 2019,
         Year!= 2020)

#Combine the wrangled flea data into one data set. This data set now has all of the wrangled flea data. 

Total_Flea_Data <- Yearly_Fleas_Samp_08to20 %>% 
  left_join(Yearly_Flea_Obs_10to20, by = "Year")

#Combine the wrangled flea data to the climate data. 

Climate_and_Flea_Data <- Climate_Means_08to18_Refined %>%
  left_join(Yearly_Flea_Obs_10to18, by = "Year") %>%
  left_join(Yearly_Fleas_Samp_08to18, by = "Year")

```

##Ear Mite Data Wrangling

```{r}
#Wrangling the ear mites sampled data

Mites_Pika_Processed <- Pika_Raw %>%
  mutate(PikaID = paste(num_r_ear,"",num_l_ear,"",code_r_ear,"",code_l_ear), Year = year(date)) %>%
  select(LTER_site:date, Year, easting:num_l_ear, ear.mites_samp, ear.mite_obs, PikaID) %>%
  group_by(Year) %>%
  subset(tag_type =="A" | tag_type == "C3") %>%
  subset(PikaID!= "NS  NS  NS  NS" & PikaID!= "NA  NA  NA  NA")

#convert ear mites sampled from a factor to numeric

Mites_Pika_Processed$ear.mites_samp <- as.numeric(as.character(Mites_Pika_Processed$ear.mites_samp))

#remove the NAs and NSs from the ear mites sampled dataset

Mites_samp_NARemoved <- Mites_Pika_Processed %>%
  select(date, Year, ear.mites_samp, PikaID) %>%
  na.omit(ear.mites_samp)
```

```{r}
#Completing the same process of splitting the data into years, grouping by individual Pika tag IDs, and finding yearly means. This time for ear mites sampled.  

Mites_samp_2008 <- Mites_samp_NARemoved %>%
  filter(Year == 2008) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2010 <- Mites_samp_NARemoved %>%
  filter(Year == 2010) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2011 <- Mites_samp_NARemoved %>%
  filter(Year == 2011) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2012 <- Mites_samp_NARemoved %>%
  filter(Year == 2012) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2013 <- Mites_samp_NARemoved %>%
  filter(Year == 2013) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2014 <- Mites_samp_NARemoved %>%
  filter(Year == 2014) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2015 <- Mites_samp_NARemoved %>%
  filter(Year == 2015) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2016 <- Mites_samp_NARemoved %>%
  filter(Year == 2016) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2017 <- Mites_samp_NARemoved %>%
  filter(Year == 2017) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2018 <- Mites_samp_NARemoved %>%
  filter(Year == 2018) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2019 <- Mites_samp_NARemoved %>%
  filter(Year == 2019) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

Mites_samp_2020 <- Mites_samp_NARemoved %>%
  filter(Year == 2020) %>%
  group_by(PikaID) %>%
  summarise(
    Mean_ear.mites_Samp = mean(ear.mites_samp),
    Year = unique(Year)
  )

#Combine the data into one data set with all yearly data. This dataset has the average ear mites found on each individual Pika for every year. 

Mites_samp_08to20 <-
  rbind(Mites_samp_2008, Mites_samp_2010, Mites_samp_2011, Mites_samp_2012, Mites_samp_2013, Mites_samp_2014, Mites_samp_2015, Mites_samp_2016, Mites_samp_2017, Mites_samp_2018, Mites_samp_2019, Mites_samp_2020)

#The above data frame within the climate data date range. 

Mites_samp_08to18 <- 
  Mites_samp_08to20 %>%
  filter(Year!= 2019,
         Year!= 2020)

# Total average ear mite samples by year

Yearly_Mite_Samp_08to20_pipe <- Mites_samp_08to20 %>%
  group_by(Year) %>%
  summarise(Yearly_ear.mite_Samp = mean(Mean_ear.mites_Samp),
            format(round(Yearly_ear.mite_Samp, 2), nsmall = 2)) 

colnames(Yearly_Mite_Samp_08to20_pipe) <- c("Year", "Average", "Proportion_ear.mite_Samp")

Yearly_Mite_Samp_08to20 <- Yearly_Mite_Samp_08to20_pipe %>%
  select(Year, Proportion_ear.mite_Samp)

#Yearly averagle ear mite samples within the climate data range. 

Yearly_Mite_Samp_08to18 <- Yearly_Mite_Samp_08to20 %>%
  filter(Year!= 2019, 
         Year!= 2020)
```

```{r}
#wrangle the mite observed data. 

Mites_obs_NARemoved <- Mites_Pika_Processed %>%
  select(Year, ear.mite_obs, PikaID) %>%
  na.omit(ear.mites_obs)

#Convert ear mites observed from a factor to a character. 

Mites_obs_NARemoved$ear.mite_obs <- as.character(Mites_obs_NARemoved$ear.mite_obs)

#select the values we want in our analysis

Selected_Mite_Obs <- Mites_obs_NARemoved %>% 
  filter(ear.mite_obs == 'NS' |
         ear.mite_obs == 'N' |
         ear.mite_obs == 'L' |
         ear.mite_obs == 'M' |
         ear.mite_obs == 'H')

#Group by year and abservation variables. 

Grouped_Mite_Obs <- Selected_Mite_Obs %>% 
  group_by(Year,ear.mite_obs) %>% 
  summarise(
    Count = n()
  )

#Pivot wider to have columns of observed variables and total counts as the variables

Mite_Obs_Counts_08to20 <- Grouped_Mite_Obs %>% 
  pivot_wider(names_from = ear.mite_obs, values_from = Count) %>%
  replace(is.na(.), 0)

Longer_Mite_Obs_Counts_08to20 <- Mite_Obs_Counts_08to20 %>%
  pivot_longer(L:H, names_to = "Observations", values_to = "TotalCounts")

#Total mite observation counts within the climate data range. 

Mite_Obs_Counts_08to18 <- Mite_Obs_Counts_08to20 %>%
  filter(Year != 2019,
         Year != 2020)
```

```{r}
#Create a data frame with all mite data

All_Mite_Data_08to20 <- Yearly_Mite_Samp_08to20 %>%
  left_join(Mite_Obs_Counts_08to20, by = "Year") 

#Create a data frame with all mite data within the climate data range 

All_Mite_Data_08to18 <- Yearly_Mite_Samp_08to18 %>%
  left_join(Mite_Obs_Counts_08to18, by = "Year")

```

#Joining of Ear Mite, Flea, and Climate Data. 

```{r}
#Create the final parasite data frame with total flea and mite data over the entire study timeline. 

Final_Parasite_DF <- Total_Flea_Data %>%
  left_join(All_Mite_Data_08to20, by = "Year") %>%
  mutate(YearNum = c(1,3,4,5,6,7,8,9,10,11,12,13)) %>%
  group_by(Year) %>%
  mutate(TotalObs = sum(L,M,N,H),
         PropL = L/TotalObs,
         PropM = M/TotalObs,
         PropN = N/TotalObs,
         PropH = H/TotalObs) 

#convert character columns to numeric so that we can run analysis and plot the data

Final_Parasite_DF$Avg_Fleas_Samp <- 
  as.numeric(Final_Parasite_DF$Avg_Fleas_Samp)

Final_Parasite_DF$Proportion_ear.mite_Samp <- 
  as.numeric(Final_Parasite_DF$Proportion_ear.mite_Samp)

#Create a final parasite data frame and combine it with the Climate Data. 

Final_Parasite_Climate_DF <- Climate_and_Flea_Data %>%
  left_join(All_Mite_Data_08to18, by = "Year")

#convert character columns to numeric so that we can run analysis and plot the data

Final_Parasite_Climate_DF$Avg_Fleas_Samp <- 
  as.numeric(Final_Parasite_Climate_DF$Avg_Fleas_Samp)

Final_Parasite_Climate_DF$Proportion_ear.mite_Samp <- 
  as.numeric(Final_Parasite_Climate_DF$Proportion_ear.mite_Samp)

#create a climate dataset without the year 2008.

No2008_Parasite_Climate_DF <- Final_Parasite_Climate_DF %>%
  filter(Year != 2008)
  
```

##Spatial Data Wrangling

```{r}
#Dropping observations without spatial data
Pika_Spatial <- Pika_Raw %>%
  mutate(PikaID = paste(num_r_ear,"",num_l_ear,"",code_r_ear,"",code_l_ear), Year = year(date)) %>%
  select(LTER_site:date, Year, easting:num_l_ear, PikaID) %>%
  group_by(Year) %>%
  drop_na(northing, easting)

#Creating a spatial dataframe of Pika captures 

Pika_Locations_sf <- Pika_Spatial %>% 
  st_as_sf(coords = c('easting','northing'),
           crs=2151)

#Calculating mean annual pika capture locations

Mean_Pika_Location <- Pika_Spatial %>%
  summarise(
    Mean_Easting = mean(easting),
    Mean_Northing = mean(northing))

Mean_Pika_Location_sf <- Mean_Pika_Location %>% 
  st_as_sf(coords = c('Mean_Easting','Mean_Northing'),
           crs=2151)
```

