---
title: "DataWrangling"
author: "Jacob Freedman and Logan Dye"
date: "2022-12-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

##Temperature Time Series Analysis

```{r}
#Temperature Time Series Analysis
Climate_Daily_Means_ts <- ts(Climate_08to18_clean$airtemp_avg_interpolated, start = c(2008,1), end = c(2018,365), frequency = 365)
Climate_Daily_trend <- Kendall::SeasonalMannKendall(Climate_Daily_Means_ts)
summary(Climate_Daily_trend)

Climate_daily_trend_decomp <- stl(Climate_Daily_Means_ts,s.window = "periodic")
```


##Regression of Pika Abundance over Time and vs. Temperature

```{r}
#Regression of Pika Counts over time

Pika_Regression <- lm(data = Pika_Total_Count, Captures ~ YearNum)
summary(Pika_Regression)

Pika_AvgTemp_Regression <- lm(data = Pika_Temperature, Captures ~ Mean_Avg_Temp)
summary(Pika_AvgTemp_Regression)
```

##Regression of Flea Observed over Time and vs. Temperature

```{r}
Flea_Obs_Regression <- lm(data = Final_Parasite_DF, Avg_Flea_Obs ~ YearNum)
summary(Flea_Obs_Regression)

Flea_Obs_AvgTemp_Regression <- lm(data = Final_Parasite_Climate_DF, Avg_Flea_Obs ~ Mean_Avg_Temp)
summary(Flea_Obs_AvgTemp_Regression)
```

##Regression of Flea Sampled over Time and vs. Temperature

```{r}
Flea_Samp_Regression <- lm(data = Final_Parasite_DF, Avg_Fleas_Samp ~ YearNum)
summary(Flea_Samp_Regression)

Flea_Samp_AvgTemp_Regression <- lm(data = Final_Parasite_Climate_DF, Avg_Fleas_Samp ~ Mean_Avg_Temp)
summary(Flea_Samp_AvgTemp_Regression)
```

##Regression of Mites Sampled over Time and vs. Temperature 

```{r}
Mite_Samp_Regression <- lm(data = Final_Parasite_DF, Proportion_ear.mite_Samp ~ YearNum)
summary(Mite_Samp_Regression)

Mites_Samp_AvgTemp_Regression <- lm(data = Final_Parasite_Climate_DF, Proportion_ear.mite_Samp ~ Mean_Avg_Temp)
summary(Mites_Samp_AvgTemp_Regression)
```

